import {createHash} from 'node:crypto';
import {z} from 'zod';
import {runAgent} from './agent.mjs';
import {unseal} from './security.mjs';
import {sendHostingerReply,validateHostingerConfig,readHostingerBody} from './hostinger-mail.mjs';
import {dayWindow,knowledgeKinds} from './workspace-data.mjs';

export const automationSchema=z.object({
 enabled:z.boolean().default(false),sourceIds:z.array(z.string().min(1).max(100)).max(30).default([]),
 matchTerms:z.array(z.string().trim().min(1).max(100)).max(30).default(['rfq','quote','pcb','pcba']),
 maxPerDay:z.number().int().min(1).max(50).default(5),instructions:z.string().max(4000).default(''),
});
export const defaultAutomation={enabled:false,enabledAt:0,sourceIds:[],matchTerms:['rfq','quote','pcb','pcba'],maxPerDay:5,instructions:''};
export function automationHash(rule){
 return createHash('sha256').update(JSON.stringify({enabled:rule.enabled,enabledAt:rule.enabledAt,sourceIds:rule.sourceIds,matchTerms:rule.matchTerms,maxPerDay:rule.maxPerDay,instructions:rule.instructions||''})).digest('hex');
}
const fingerprint=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
function recordFingerprint(row){
 if(!row)return '';
 const value={id:row.id,kind:row.kind,title:row.title||'',content:typeof row.content==='string'?row.content:row.body||'',site:row.site||'',projectId:row.projectId||'',url:row.url||'',truncated:!!row.truncated};
 if(['inquiries','mic'].includes(row.kind))Object.assign(value,{sender:row.sender||'',sourceId:row.sourceId||'',externalId:row.externalId||'',mailbox:row.mailbox||'',receivedAt:row.receivedAt||'',messageId:row.messageId||'',autoGenerated:!!row.autoGenerated});
 return fingerprint(value);
}
function sourceFingerprint(source){
 if(!source)return '';
 const cfg=source.config||{};
 return fingerprint({id:source.id,type:source.type,site:source.site||'',enabled:!!source.enabled,mailboxId:cfg.mailboxId||'',user:(cfg.user||'').toLowerCase(),folder:cfg.folder||'INBOX',secret:source.secret||''});
}
export function replyAddress(sender){
 const text=String(sender||'').trim();if(!text||/[\r\n,;]/.test(text))return '';
 const bracket=text.match(/^[^<>]*<([^<>]+)>\s*$/),value=(bracket?bracket[1]:text).trim();
 return /^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(value)?value.toLowerCase():'';
}
function autoEnvelopeEligible(mail,source,rule,now=Date.now()){
 const at=Date.parse(mail?.receivedAt),to=replyAddress(mail?.sender);
 if(!rule?.enabled||!rule.enabledAt||!source?.enabled||source.type!=='hostinger'||!rule.sourceIds?.includes(source.id)||mail?.sourceId!==source.id||!['new','following'].includes(mail.status))return false;
 if(!Number.isFinite(at)||at<rule.enabledAt||at>now+300000||!to||to===source.config.user?.toLowerCase()||mail.autoGenerated)return false;
 if((source.config.folder||'INBOX').toUpperCase()!=='INBOX'||/no.?reply|do.?not.?reply|mailer-daemon|postmaster|bounce/i.test(to))return false;
 if(/^\s*(re\s*:|fwd?\s*:|自动回复|自动回覆|auto(?:matic)?[ -]?reply|out of office)/i.test(mail.title||''))return false;
 return true;
}
export function autoEligible(mail,source,rule,now=Date.now()){
 if(!autoEnvelopeEligible(mail,source,rule,now))return false;
 const text=((mail.title||'')+' '+(mail.content||'')).toLowerCase();
 return (rule.matchTerms||[]).some(term=>text.includes(term.toLowerCase()));
}
export async function createReply(store,key,input,{agentRequest}={}){
 const item=await store.get(input.inquiryId);
 if(!item||!['inquiries','mic'].includes(item.kind))throw Object.assign(new Error('询盘不存在'),{status:404});
 const old=await store.getReply(item.id);if(old&&['sending','sent','uncertain'].includes(old.status))throw Object.assign(new Error('这封询盘已有发送记录，请先核对'),{status:409});
 const initialSource=item.sourceId?await store.getSource(item.sourceId):null;
 // Capture the actual read_record inputs, including a freshly hydrated body. A
 // revision between paginated reads must not form one supposedly complete input.
 const evaluated=new Map(),changed=new Set();
 function capture(row){
  if(!row)return;
  const hash=recordFingerprint(row),prior=evaluated.get(row.id);
  if(prior&&prior!==hash)changed.add(row.id);
  evaluated.set(row.id,hash);
 }
 const observed=Object.create(store);
 observed.get=async id=>{const row=await store.get(id);capture(row);return row;};
 observed.save=async(record,version)=>{const row=await store.save(record,version);evaluated.set(row.id,recordFingerprint(row));return row;};
 const run=await runAgent(observed,key,{action:'reply',inquiryId:item.id,site:input.site||item.site||'',projectId:input.projectId||'',prompt:input.prompt||'',date:input.date},{...(agentRequest?{request:agentRequest}:{})});
 if(!run.reply)throw new Error('模型未返回回复草稿，请重试');
 const current=await store.get(item.id);
 if(!current)throw Object.assign(new Error('询盘已删除，请重新选择'),{status:409});
 const source=current.sourceId?await store.getSource(current.sourceId):null;
 const from=source?.config?.user||current.mailbox||'',to=replyAddress(current.sender),refs=[],knowledgeFingerprints={};
 let inputsChanged=changed.has(item.id)||evaluated.get(item.id)!==recordFingerprint(current)||sourceFingerprint(initialSource)!==sourceFingerprint(source);
 for(const id of run.reply.sourceIds||[]){
  const record=await store.get(id),hash=evaluated.get(id);
  if(!hash||changed.has(id)||hash!==recordFingerprint(record))inputsChanged=true;
  if(record&&knowledgeKinds.includes(record.kind)){refs.push({id:record.id,title:record.title,kind:record.kind,url:record.url||''});knowledgeFingerprints[id]=hash;}
 }
 const missing=[...(run.reply.missingInfo||[])];if(!refs.length&&!missing.length)missing.push('知识库未明确，需人工核对回复');
 if(current.truncated&&!missing.includes('询盘正文不完整'))missing.push('询盘正文不完整');
 if(inputsChanged)missing.push('询盘、邮箱或知识资料在生成期间已变更，请重新生成并核对');
 const evaluation={inquiry: evaluated.get(item.id)||'',source:sourceFingerprint(initialSource),knowledge:knowledgeFingerprints};
 const value={inquiryId:current.id,sourceId:current.sourceId||'',from,to,subject:run.reply.subject,body:run.reply.body,sourceIds:refs.map(r=>r.id),sources:refs,evaluation,missingInfo:missing,isInquiry:run.reply.isInquiry===true,readyToSend:run.reply.readyToSend===true&&refs.length>0&&!missing.length&&!!to&&!current.truncated,model:run.model,runId:run.id,automatic:!!input.automatic,autoEvaluatedAt:input.automatic?Date.now():0,policyHash:input.policyHash||'',status:'draft',createdAt:old?.createdAt};
 return store.saveReply(value,old?.version||0);
}
async function automaticPermission(store,inquiryId,draft,now){
 const rule={...defaultAutomation,...await store.getSetting('agent-automation')},item=await store.get(inquiryId),source=item?.sourceId?await store.getSource(item.sourceId):null;
 if(!autoEligible(item,source,rule,now)||draft.policyHash!==automationHash(rule))throw new Error('自动回复已暂停或规则已更新');
 if(!draft.readyToSend||!draft.isInquiry||draft.missingInfo?.length||!draft.sourceIds?.length||draft.humanEditedAt)throw new Error('自动回复需要知识库依据且没有待确认项');
 if(item.truncated||!item.content?.trim()||!draft.evaluation||draft.evaluation.inquiry!==recordFingerprint(item)||draft.evaluation.source!==sourceFingerprint(source))throw new Error('评估过的询盘或邮箱已变更，请重新生成回复');
 for(const id of draft.sourceIds){const record=await store.get(id);if(!record||!knowledgeKinds.includes(record.kind)||!draft.evaluation.knowledge?.[id]||draft.evaluation.knowledge[id]!==recordFingerprint(record))throw new Error('自动回复的知识库资料已变更或失效');}
 return rule;
}
export async function sendReply(store,key,inquiryId,{version,automatic=false}={},options={}){
 const item=await store.get(inquiryId),draft=await store.getReply(inquiryId);
 if(!item||item.kind!=='inquiries'||!draft)throw Object.assign(new Error('邮件或回复草稿不存在'),{status:404});
 const source=await store.getSource(item.sourceId);
 if(source?.type!=='hostinger'||!source.secret)throw new Error('该来源尚未接入发信接口，请使用已配置的 Hostinger 邮箱');
 const cfg=validateHostingerConfig(source),to=replyAddress(item.sender);
 if(!to||draft.to.toLowerCase()!==to||draft.from.toLowerCase()!==cfg.user.toLowerCase()||draft.sourceId!==source.id)throw new Error('收件人或发件邮箱与原询盘不匹配，请重新生成草稿');
 if(!draft.subject?.trim()||/[\r\n]/.test(draft.subject)||draft.subject.length>500||!draft.body?.trim()||draft.body.length>20000)throw new Error('邮件主题或正文格式无效');
 const captured={inquiry:recordFingerprint(item),source:sourceFingerprint(source),to,from:cfg.user.toLowerCase(),externalId:item.externalId};
 const now=Date.now(),rule=automatic?await automaticPermission(store,inquiryId,draft,now):null;
 const claim=await store.claimReply(inquiryId,Number(version),{automatic,now,dayStart:dayWindow().start,maxPerDay:rule?.maxPerDay||5});
 try{
  await sendHostingerReply(source,unseal(source.secret,key,source.id),captured.externalId,{to:captured.to,subject:claim.reply.subject,body:claim.reply.body},{...options,beforeSend:async()=>{
   if(automatic)await automaticPermission(store,inquiryId,claim.reply,Date.now());
   const current=await store.get(inquiryId),currentSource=current?.sourceId?await store.getSource(current.sourceId):null;
   if(recordFingerprint(current)!==captured.inquiry||sourceFingerprint(currentSource)!==captured.source||replyAddress(current?.sender)!==captured.to||current?.externalId!==captured.externalId||(currentSource?.config?.user||'').toLowerCase()!==captured.from)throw new Error('原邮件、收件人或邮箱配置已变更，请重新核对');
  }});
  return await store.finishReply(inquiryId,claim.lease,{status:'sent'});
 }catch(error){
  const status=error.noSend||[400,401,403,404,422,429].includes(error.statusCode)?'failed':'uncertain';
  await store.finishReply(inquiryId,claim.lease,{status,error:status==='uncertain'?'发信结果不明确，请先核对原邮箱已发送文件夹':'发送未完成，请检查邮箱授权或规则'});
  throw Object.assign(new Error(status==='uncertain'?'发信结果不明确，已停止重试。请先在原邮箱已发送文件夹核对':'未发送邮件，请检查邮箱授权或自动回复规则'),{status:502});
 }
}
export async function runAutoReplies(store,key,options={}){
 const rule={...defaultAutomation,...await store.getSetting('agent-automation')};
 if(!rule.enabled)return {enabled:false,processed:0,sent:0};
 const lease=await store.claimJob('auto-replies',Date.now(),1200000);
 if(!lease)return {enabled:true,processed:0,sent:0,skipped:true};
 let processed=0,sent=0,needsReview=0;
 try{
  const sources=new Map((await store.listSources()).map(s=>[s.id,s]));let candidate;
  for(let offset=0;!candidate;offset+=100){
   const rows=await store.list('inquiries',{limit:100,offset});
   for(let mail of rows.items){
    const source=sources.get(mail.sourceId);
    if(!autoEnvelopeEligible(mail,source,rule)||await store.getReply(mail.id))continue;
    if(!mail.content){
     const detail=await readHostingerBody(source,unseal(source.secret,key,source.id),mail.externalId,options),fresh=await store.get(mail.id);
     mail=await store.save({...fresh,...detail,readAt:fresh.readAt||Date.now()},fresh.version);
    }
    if(autoEligible(mail,source,rule)){candidate=mail;break;}
   }
   if(offset+rows.items.length>=rows.total||!rows.items.length)break;
  }
  if(!candidate)return {enabled:true,processed,sent};
  const existing=await store.listReplies({automatic:true,from:dayWindow().start,limit:100});
  if(existing.items.filter(r=>['sending','sent','uncertain'].includes(r.status)).length>=rule.maxPerDay)return {enabled:true,processed,sent,limitReached:true};
  const generate=options.generate||((s,k,input)=>createReply(s,k,input,{agentRequest:options.agentRequest}));
  const draft=await generate(store,key,{inquiryId:candidate.id,automatic:true,policyHash:automationHash(rule),prompt:rule.instructions+'\n为自动回复起草，请判断是否真实询盘；只在知识库内容充分、没有缺失或冲突时标记 readyToSend。'});
  processed=1;
  if(draft.readyToSend&&draft.isInquiry&&!draft.missingInfo?.length&&draft.sourceIds?.length){await sendReply(store,key,candidate.id,{version:draft.version,automatic:true},options);sent=1;}else needsReview=1;
  await store.setSetting('agent-automation-state',{checkedAt:Date.now(),processed,sent,needsReview,error:''});
  return {enabled:true,processed,sent,needsReview};
 }catch(error){
  await store.setSetting('agent-automation-state',{checkedAt:Date.now(),processed,sent,needsReview,error:'自动回复未完成，请在邮件详情核对草稿或发送状态'});
  return {enabled:true,processed,sent,needsReview,failed:true};
 }finally{await store.releaseJob('auto-replies',lease);}
}
